# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy To Central

on:
  push:
    branches:
       - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: OSSRH_USERNAME # env variable for username in deploy
        server-password: OSSRH_TOKEN # env variable for token in deploy
    
    - name: Set up GPG
      run: |
        echo "$GPG_PRIVATE_KEY" > private.asc
        gpg --import --batch private.asc
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    
    - name: Perform Release
      run: mvn --batch-mode clean deploy -P release
      env:
        OSSRH_USERNAME: ruediste
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
